title: Kyle Olivo
email: kyle@kyleolivo.com
description: >-
  Let's build!
baseurl: ""
url: "https://kyleolivo.github.io"
twitter_username: kyleolivo
github_username:  kyleolivo
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Kyle Olivo"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Wanderer. Lover of learning."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.kyleolivo.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kyleolivo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kyleolivo"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kyleolivo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kyleolivo"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
